namespace: ns-webhooks-env

resources:
- DefaultConnection
- storageMigrations
- apiservice
- cache
- webfrontend
- namespace.yaml
- dashboard.yaml

generatorOptions:
  disableNameSuffixHash: true


transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: notImportantHere
      namespace: ns-webhooks-env
    unsetOnly: true