services:
    web:
        image: helix26xyz/webhooks-dotnet/web:latest
        build:
            context: .
            dockerfile: webhooks.Web/Dockerfile
        ports:
            - "5000:8080"
            - "6000:443"
        depends_on:
            - apiservice
        volumes:
            - ./docker.appsettings.json:/app/appsettings.json:ro
          
    apiservice:
        image: helix26xyz/webhooks-dotnet/apiservice:latest
        build:
            context: .
            dockerfile: webhooks.ApiService/Dockerfile
             
        ports:
            - "5001:8080"
            - "6001:443"
            - "5001:5001" # Expose WebSocket port
        depends_on:
            - storagemigrations
        volumes:
            - ./docker.appsettings.json:/app/appsettings.json:ro
    storagemigrations:
        image: helix26xyz/webhooks-dotnet/storagemigrations:latest
        build:
            context: .
            dockerfile: webhooks.StorageMigrations/Dockerfile
        ports:
            - "5002:8080"
            - "6002:443"
        volumes:
            - ./docker.appsettings.json:/app/appsettings.json:ro

    websocketdemoclient:
        image: helix26xyz/webhooks-dotnet/websocketdemoclient:latest
        build:
            context: .
            dockerfile: webhooks.WebSocketDemoClient/Dockerfile
        ports:
            - "5003:8080"
            - "6003:443"
        depends_on:
            - apiservice
        volumes:
            - ./docker.appsettings.json:/app/appsettings.json:ro
