resources:
- deployment.yaml
- service.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: defaultconnection-env
  literals:
    - ACCEPT_EULA=Y
    - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire-dashboard:18889
    - OTEL_SERVICE_NAME=DefaultConnection

# secretGenerator:
# - name: defaultconnection-secrets
#   envs:
#   - .defaultconnection.secrets
