---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storagemigrations
  labels:
    app: storagemigrations
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: storagemigrations
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: storagemigrations
    spec:
      containers:
      - name: storagemigrations
        image: ghcr.io/helix26xyz/webhooks-dotnet-storagemigrations:main
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        envFrom:
        - configMapRef:
            name: storagemigrations-env
        - secretRef:
            name: storagemigrations-secrets
      terminationGracePeriodSeconds: 180
