---
apiVersion: batch/v1
kind: Job
metadata:
  name: storagemigrations
  labels:
    app: storagemigrations
  annotations:
    # Force Flux to recreate this job on each reconciliation
    kustomize.toolkit.fluxcd.io/force: "enabled"
spec:
  # Clean up completed jobs after 5 minutes
  ttlSecondsAfterFinished: 300
  backoffLimit: 0 # Do not retry the job if it fails
  template:
    metadata:
      labels:
        app: storagemigrations
    spec:
      restartPolicy: Never
      containers:
      - name: storagemigrations
        image: ghcr.io/helix26xyz/webhooks-dotnet-storagemigrations:main
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        envFrom:
        - configMapRef:
            name: storagemigrations-env
        - configMapRef:
            name: storagemigrations-version
        - secretRef:
            name: storagemigrations-secrets
      terminationGracePeriodSeconds: 180
